#!/usr/bin/env python3
"""
gallery-update.py
-----------------
Run from the project root after adding images to uploads/ or assets/:

    python3 gallery-update.py

Scans both folders, deduplicates (assets/ wins over uploads/ for same filename),
filters out logos/icons/screenshots, then writes:

    ui_kits/website/gallery-manifest.js

The Results/Gallery page loads that file automatically.
"""

import os
import re
from pathlib import Path
from urllib.parse import quote

# ── Paths ──────────────────────────────────────────────────────────────────
ROOT     = Path(__file__).parent
UPLOADS  = ROOT / "uploads"
ASSETS   = ROOT / "assets"
OUTPUT   = ROOT / "ui_kits" / "website" / "gallery-manifest.js"

# ── Config ─────────────────────────────────────────────────────────────────
IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".webp"}

MIN_BYTES = 20_000   # anything under 20 KB is likely an icon or thumbnail

# Exact filenames to always skip
SKIP_NAMES = {
    "logo.png", "icon-192.png", "icon.png",
    "android-chrome-192x192.png", "favicon.ico",
    "review1.png", "review2.png", "review3.png",
    "test.png", "test.jpg",
}

# ── Categorization ─────────────────────────────────────────────────────────
def categorize(filename: str):
    """Return (cat, label, alt_text) based on filename."""
    n = filename.lower()

    if re.search(r"upholstery|upholestry|couch|sofa|chair|dining|blueseats|sectional|fabric|couchh", n):
        return ("upholstery", "Upholstery", "Upholstery cleaning result")

    if re.search(r"business|commercial|office|church|school|college|library|restau|tmobile|dickinson|facility|realhchurch", n):
        return ("commercial", "Commercial", "Commercial carpet cleaning job")

    if re.search(r"stain|spot|petstain|pet[ab]|odor", n):
        return ("stains", "Stains", "Stain treatment result")

    if re.search(r"before|after|dirty|blueba", n):
        return ("before-after", "Before &amp; After", "Carpet cleaning before and after")

    if re.search(r"^van", n):
        return ("carpet", "Carpet", "Carpet Guys service van")

    if re.search(r"award", n):
        return ("carpet", "Carpet", "Best of Harrisburg 2023 award")

    return ("carpet", "Carpet", "Carpet cleaning result")


# ── Collect unique images ──────────────────────────────────────────────────
# Pass 1: uploads/ — then assets/ overwrites same lowercase name.
# Pass 2: size deduplication — if two different-named files share the exact
#          same byte count they are almost certainly the same photo.
#          Keep assets/ version; if both from same folder, keep first.

images: dict[str, Path] = {}

for folder in [UPLOADS, ASSETS]:
    if not folder.exists():
        continue
    for f in sorted(folder.iterdir()):
        if not f.is_file():
            continue
        if f.suffix.lower() not in IMAGE_EXTS:
            continue
        if f.name.lower() in SKIP_NAMES:
            continue
        try:
            size = f.stat().st_size
        except OSError:
            continue
        if size < MIN_BYTES:
            continue
        images[f.name.lower()] = f   # assets/ overwrites uploads/ for same name

# Size deduplication: keep assets/ when two files share identical byte counts
seen_sizes: dict[int, Path] = {}
deduplicated: dict[str, Path] = {}

# Sort so assets/ files come after uploads/ (assets wins)
for key, path in sorted(images.items(), key=lambda x: (0 if str(x[1].parent) == str(UPLOADS) else 1, x[0])):
    size = path.stat().st_size
    if size in seen_sizes:
        prev = seen_sizes[size]
        # Keep whichever is from assets/; if both same folder, keep first
        if str(path.parent) == str(ASSETS):
            # Replace the uploads version
            old_key = prev.name.lower()
            if old_key in deduplicated:
                del deduplicated[old_key]
            deduplicated[key] = path
            seen_sizes[size] = path
        # else: keep the existing (already assets or first seen)
    else:
        seen_sizes[size] = path
        deduplicated[key] = path

images = deduplicated

# Sort alphabetically by lowercase name for stable output
sorted_images = sorted(images.items(), key=lambda x: x[0])


# ── Generate JS ────────────────────────────────────────────────────────────
lines = [
    "// ─────────────────────────────────────────────────────────────────────",
    "// gallery-manifest.js",
    "// Auto-generated by gallery-update.py — do not edit this file manually.",
    "// To add new images: drop them in uploads/ or assets/, then run:",
    "//   python3 gallery-update.py",
    "// ─────────────────────────────────────────────────────────────────────",
    f"// Total: {len(sorted_images)} images",
    "var GALLERY_IMAGES = [",
]

for _, path in sorted_images:
    if str(path.parent) == str(ASSETS):
        folder = "../../assets"
    else:
        folder = "../../uploads"

    encoded = quote(path.name)
    src = f"{folder}/{encoded}"
    cat, label, alt = categorize(path.name)
    lines.append(f"  {{ src:'{src}', alt:'{alt}', cat:'{cat}', label:'{label}' }},")

lines.append("];")

OUTPUT.parent.mkdir(parents=True, exist_ok=True)
OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

print(f"gallery-manifest.js updated — {len(sorted_images)} images")
for _, path in sorted_images:
    print(f"  {path.relative_to(ROOT)}")
